### ISSUE TITLE
legobot functions that should not be public should be started with _

### ISSUE THREAD

**Issue by gumpcraca** [bbriggs/Legobot#19]
>>> dir(myBot)
['__doc__', '__init__', '__module__', '_legoBot__listen', 'addDefaultFunc', 'addFunc', 'addRandTimerFunc', 'addTimerFunc', 'batchAddFunc', 'chans', 'connect', 'defaultFunc', 'defaultFuncChar', 'defaultHelp', 'func', 'funcHelp', 'host', 'hostpw', 'logfunc', 'nick', 'port', 'randTimerFuncList', 'sendMsg', 'threadList', 'threadQueue', 'timerFuncList']

lots of these should not be accessed.

**Comment by gumpcraca** [comment]
This would make us not backwards compatible. May need to defer this for a while.

**Comment by bbriggs** [comment]
That would be a major version bump. Create a 1.0.0 milestone and add this to it.

**Comment by gumpcraca** [comment]
rethought this. if they're not expected to be accessed by end users, then we should just be able to refactor. No users should be setting legobot.host or legobot.port, those should be set on init.

**Comment by bbriggs** [comment]
Sorry, I should have read this through more thoroughly before. 

Which one are you wanting to mangle namespace on? Of the ones you listed originally, methods like addFunc need to be accessed by the user.
