### ISSUE TITLE
multiline responses are not handled appropriately

### ISSUE THREAD

**Issue by gumpcraca** [bbriggs/Legobot#23]
split responses back from functions, turn them into separate responses using the same dest room/person

**Comment by bbriggs** [comment]
currently we're just returning a single tuple of `(response,target)`. How do you propose breaking multi-line responses up?

It seems to me like we would have to return an array of tuples, then the send method of legobot would have to iterate through that list and fire it back. This would leave the potential for a crafted array to return multiple unique responses to different people simultaneously.

**Comment by gumpcraca** [comment]
This is resolved in dev, last PR
