### ISSUE TITLE
abstract messaging platform from LegoBot - Use "adapters"

### ISSUE THREAD

**Issue by gumpcraca** [bbriggs/Legobot#28]
Create an "IRC Adapter" that would be passed into legobot, Legobot would connect to each adapter, listen on those adapters and respond back to them in kind.

This would allow people to write their own adapter for Legobot, Probably should create a "GenericAdapter" class that can be subclassed with abstract base class assertions. Every adapter should have some minimum level of things. Probably a "connect" def, "reply" def, etc, ways to interact with the "Service".  After that, legobot would leverage the same architechture to parse messages, thread/call functions and respond appropriately.

The Legobot team could write a set of adapters, IRC, Spark, XMPP, GChat, etc to start with and allow the community to write any additional ones needed.

**Comment by bbriggs** [comment]
Resolved in #52
