### ISSUE TITLE
Rearchitect how functions are stored

### ISSUE THREAD

**Issue by gumpcraca** [bbriggs/Legobot#3]
Idea is to: 
1. Create a separate py file for each function stored in $INSTALL_DIR/scripts/
2. Add a !rehash function that will re-import the functions that have changed and import new functions, will need to use the reload function to do this: https://docs.python.org/2/library/functions.html#reload

**Comment by bbriggs** [comment]
Work on this in the add-script-dir branch, please.

**Comment by bbriggs** [comment]
This will break backwards compatibility, I think.

**Comment by bbriggs** [comment]
Resolved in #52
