### ISSUE TITLE
provide method to persistence to data

### ISSUE THREAD

**Issue by gumpcraca** [bbriggs/Legobot#4]
something like
legobot.save_state(var)
legobot.fetch_state(var)

The fetch function would be transactional, but the save function would work differently, when the function called the save state function, it would be writing into a queue object. There would be a persistent thread spun up as a "write to sql/whateverdb" method, that method would look for new objects in the queue and write those accordingly. Using queue.get with default args should block until we put something in the queue.

**Comment by bbriggs** [comment]
use mkstemp() 
https://docs.python.org/2/library/tempfile.html

**Comment by bbriggs** [comment]
We decided to push this off to the user and suggest using ConfigParser.

**Comment by bbriggs** [comment]
Example: [tip_user.py](https://github.com/bbriggs/Legobot-examples/blob/master/legos/tip_user.py)
