### ISSUE TITLE
Legobot randomly reboots

### ISSUE THREAD

**Issue by Recon419A** [bbriggs/Legobot#40]
TheDoctor has quit ()
Recon419: Uh-oh.
Recon419: Is that supposed to happen?
TheDoctor (TheDoctor@lolumadbro?) has joined

**Comment by bbriggs** [comment]
Need to investigate whether this is an issue with hosting/deployment or Legobot itself. Since this is for a specific instance of Legobot, file the issue [here](https://github.com/bbriggs/sithmail-tipbot)
