### ISSUE TITLE
IRCConnector needs to support multiple channels

### ISSUE THREAD

**Issue by bbriggs** [bbriggs/Legobot#59]

**Comment by Mikepicker** [comment]
I tested the code and it looks like it already implements this functionality. By running the tutorial code on the readme the bot can successfully log to 3 different channels and respond correctly in all of them. Can someone else confirm this?

**Comment by bbriggs** [comment]
Which branch did you do this on? This should be fine to do on `master`, but `develop` is a complete rewrite to get to 1.0.x (Maybe I should put that in the readme on `master`? 😛)
