### ISSUE TITLE
rename example legobot from Legobot.py to anything else

### ISSUE THREAD

**Issue by gumpcraca** [bbriggs/Legobot#88]
having this named the same thing as the package causes issues like:
>>> import Legobot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kmccabe2/Legobot.py", line 3, in <module>
    from Legobot.Lego import Lego
ImportError: No module named 'Legobot.Lego'; 'Legobot' is not a package
No module named 'Legobot.Lego'; 'Legobot' is not a package

**Comment by bbriggs** [comment]
Done
